### ISSUE TITLE
Toplantı Notları

### ISSUE THREAD

**Issue by Voxmundi** [Voxmundi/Cuse#7]
bir kaç aylık renew seçeneği eklenecek
Delet buttonunun yanına renew gelecek
Bussiness ve Individual ayrımı eklenecek 
Disrict bilgilerini Kaan yollayacak

**Comment by Tetherclub** [comment]
Business Profile Form
Indivudual Profile Form
Ad creation Form
Ipad de grid ve bir evin detayi guzel cikmiyor cozum bulunmasi lazim
Font Gondericem
Footnote ve Header bolgesi duzeltilecek
Haritada Zoom-in, yavas yavas insin

Duzeltilecek
