### ISSUE TITLE
Formlarda sorulacaklar

### ISSUE THREAD

**Issue by Tetherclub** [Voxmundi/Cuse#8]
LEGEND:  
" * " going to be asked in the advance search
" ^ " appear on minimized search
" # " appear on ad itself
" + " can be drop down menu
(iconized as much as possible)

Business Profile Form

Company Name
Phone
Email Address
Address
Company Description
Logo
Create , Confirm Password
Terms & Conditions
Newsletters/ E-news
Required Documents from tenants( guarantor's form, application forms, ext...)

Individual Profile Form

First Name
Last Name
Phone Number
Email Address
Address(optional)
Create, Confirm Password
Terms & Conditions
Newsletters/ E-news
Major
" * ^ #  +"Personal Interests: Study,Night life, Cafe/Res, Downtown/Shopping, Recreation, Greek Life, Culture/art, Quiet/Relaxation, Grad.

AD CREATION FORM
Map(adjustments we talked about)

" * + " Amenities:
" ^ # "Parking
" ^ # "Pet friendly
Smoking Friendly,Non-Smoking
Balcony/Porch
Kitchen
Dishwasher
Bathrooms
Fireplace
" ^ # "Furnished, Not Furnished
Wheelchair Accesible
Elevator in building
Buzzer/intercom

" * " Utilities:
" ^ # "Water cooling/heating
" ^ # "Electricity
Gas
Ac
Laundry in Unit
Laundry on Site
" ^ # "Wi-Fi
Cable TV
Maintenance

" * " Safety Features:( Measuring safety of properties listed)
Smoke Detector
Carbon monoxide detector
Fire Extinguisher
First Aid Kit
Camera Surveillance

" * ^ # " Kinds of Properties:

Apartment
Room
House

" * ^ " Academic Sessions:
Fall
Spring
May-mester
Summer I
Summer II

" * ^ #  " Bedroom count:
1
2
3
4
5+

" * ^ #  "Rent
" * " Location/Area
" * " Distance to Quad
Ad Type

" * ^ # " Move in / Move out dates:
Now or ASAP
Specific Date

Description
Upload Pictures

**Comment by Voxmundi** [comment]
ok
