### ISSUE TITLE
FONT LIST

### ISSUE THREAD

**Issue by Tetherclub** [Voxmundi/Cuse#9]
Google Fonts dan su secilenler kullanilabilir.

Poiret One
Limelight
Mont Serras Alternatives
Julius Sans One
Monoton
Work Sans
Gill Sans(*)

hangisi sence designa en cok yakisirsa onu kullan, son olarak senin kararin.

**Comment by Voxmundi** [comment]
Mont Serras Alternatives kullandım

**Comment by Tetherclub** [comment]
Guzel secim

**Comment by Tetherclub** [comment]
Ince Fontlar:

Poiret One
Josefin Sans
Open Sans

Bunlarin kendi icerisinde incelik ve kalinlik ayarlari var, onlari kullanarakda halledebiliriz.
